"""
TOKEN TYPES DEFINITIONS
"""
SPACE = 'SPACE'
TAB = 'TAB'
OPEN_PAR = 'OPEN_PAR'
CLOSING_PAR = 'CLOSING_PAR'
PLUS = 'PLUS'
MINUS = 'MINUS'
MULT = 'MULT'
DIV = 'DIV'
EQUAL = 'EQUAL'
WORD_VAR = 'WORD_VAR'
TERMINATOR = 'TERMINATOR'
IDENTIFIER = 'IDENTIFIER'
NUMBER = 'NUMBER'
STRING = 'STRING'

EOF = 'EOF'
